package:
  name: vinautil
  version: 0.0.3

source:
  path: /home/lyzeng/vinautil

build:
  number: 5
  skip: True  # [not linux64]
#  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >3.8
    - conda-forge::pyyaml
    - pip
    - setuptools
    - git
  run:
    - python >3.8
    - conda-forge::pandas
    - conda-forge::openbabel
    - conda-forge::rdkit
    - conda-forge::pymol-open-source
    - conda-forge::loguru
    - conda-forge::numpy
    - conda-forge::swig
    - conda-forge::boost-cpp
    - conda-forge::sphinx
    - conda-forge::sphinx_rtd_theme
    - conda-forge::vina
    - conda-forge::ipython
    - conda-forge::peewee
    - conda-forge::scipy
    - conda-forge::prody # meeko dependecy (optionally, for covalent docking)

about:
  home: https://github.com/hotwa/vinautil.git
  license: MIT
  summary: 'autodock vina tools'
  description: |
    for autodock vina transform pqbqt to mol2, restore chemical bond information. 
    make config file for autodock vina. add SCARdock
  dev_url: https://github.com/hotwa/vinautil.git
  doc_url: https://github.com/hotwa/vinautil.git
  doc_source_url: https://github.com/hotwa/vinautil.git
