package:
  name: vinautil
  version: 0.0.1

source:
  path: C:/Users/user/hotwaprogram/vinautil_conda

build:
  noarch: python
  number: 0
#  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >3.8
    - pip
    - setuptools
    - openbabel >3.0.0
    - pandas >1.2.0
    - rdkit
    - pymol-open-source
    - loguru
  run:
    - python >3.8
    - pandas >1.2.0
    - openbabel >3.0.0
    - rdkit
    - pymol-open-source
    - loguru

about:
  home: https://github.com/hotwa/vinautil.git
  license: MIT
  summary: 'autodock vina tools'
  description: |
    for autodock vina transform pqbqt to mol2, restore chemical bond information. 
    make config file for autodock vina.
  dev_url: https://github.com/hotwa/vinautil.git
  doc_url: https://github.com/hotwa/vinautil.git
  doc_source_url: https://github.com/hotwa/vinautil.git