package:
  name: vinautil
  version: 0.0.7

source:
  path: .

build:
  number: 4
  skip: True  # [not linux64]
#  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python =3.10
    - conda-forge::pyyaml
    - pip
    - setuptools
    - git
  run:
    - python =3.10
    - conda-forge::pdbfixer
    - conda-forge::openmm
    - bioconda::mgltools
    - conda-forge::spyrmsd
    - conda-forge::pandas
    - conda-forge::openbabel
    - conda-forge::rdkit
    - conda-forge::pymol-open-source 2.5.0 py310h292d129_6
    - conda-forge::loguru
    - conda-forge::swig
    - conda-forge::boost-cpp 
    - conda-forge::sphinx
    - conda-forge::sphinx_rtd_theme
    - conda-forge::vina 1.2.3 py310he924329_2
    - conda-forge::ipython
    - conda-forge::biopython
    - conda-forge::prody # meeko dependecy (optionally, for covalent docking)

about:
  home: https://github.com/hotwa/vinautil.git
  license: MIT
  summary: 'autodock vina tools'
  description: |
    for autodock vina transform pqbqt to mol2, restore chemical bond information. 
    make config file for autodock vina. add SCARdock
  dev_url: https://github.com/hotwa/vinautil.git
  doc_url: https://github.com/hotwa/vinautil.git
  doc_source_url: https://github.com/hotwa/vinautil.git
