package:
  name: vinautil
  version: 0.0.1

source:
  path: C:/Users/Admin/program/vinautil

build:
  noarch: python
  number: 0
  script:
    # - pip install vina

requirements:
  host:
    - python >3.8
    - pip
    - setuptools
  run:
    - python >3.8
    - pandas >1.2.0
    - conda-forge::openbabel >3.0.0
    - conda-forge::rdkit
    - conda-forge::pymol-open-source
    - conda-forge::loguru
    - conda-forge::numpy
    - conda-forge::swig
    - conda-forge::boost-cpp
    - conda-forge::sphinx
    - conda-forge::sphinx_rtd_theme

about:
  home: https://github.com/hotwa/vinautil.git
  license: MIT
  summary: 'autodock vina tools'
  description: |
    for autodock vina transform pqbqt to mol2, restore chemical bond information. 
    make config file for autodock vina. add SCARdock
  dev_url: https://github.com/hotwa/vinautil.git
  doc_url: https://github.com/hotwa/vinautil.git
  doc_source_url: https://github.com/hotwa/vinautil.git
